name: Create and Upload Packages.gz (Manual)

on:
  workflow_dispatch:

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Packages.gz
        run: |
          mkdir -p out
          tar -czf out/Packages.gz . --exclude=.git --exclude=out

      - name: Upload Packages.gz to latest GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Packages.gz
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
