name: Create and Upload Packages.gz (Manual)

on:
  workflow_dispatch:

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Packages.gz (from source dir)
        run: |
          mkdir -p out
          tar --exclude='.git' --exclude='out' -czf Packages.gz *
          mv Packages.gz out/

      - name: Upload Packages.gz to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Packages.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
