name: Create and Upload Packages.gz (Manual)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating a release and uploading files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Packages.gz (from source dir)
        run: |
          mkdir -p out
          tar --exclude='.git' --exclude='out' -czf Packages.gz *
          mv Packages.gz out/

      - name: Download Packages.sig using curl
        run: |
          curl -O https://immortalwrt.kyarucloud.moe/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/base/Packages.sig

      - name: Create Git Tag
        id: create_tag
        run: |
          # Generate a timestamp-based version tag
          VERSION=$(date +v%Y%m%d-%H%M%S)
          echo "Generated tag: $VERSION"
          git tag $VERSION
          git push origin $VERSION

      - name: Upload Packages.gz and Packages.sig to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Packages.gz,Packages.sig  # Upload both files
          tag_name: ${{ steps.create_tag.outputs.VERSION }}  # Use the generated version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
