name: Create and Upload Packages.gz

on:
  release:
    types: [published]

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Packages.gz
        run: |
          mkdir -p out
          tar -czvf out/Packages.gz . --exclude='./.git' --exclude='./out'

      - name: Upload Packages.gz to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Packages.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
