name: Create and Upload Packages.gz (Manual)

on:
  workflow_dispatch:

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating a release and uploading files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Packages.gz (from source dir)
        run: |
          mkdir -p out
          tar --exclude='.git' --exclude='out' -czf Packages.gz *
          mv Packages.gz out/

      - name: Create Git Tag
        id: create_tag
        run: |
          VERSION="v1.0.0"
          git tag $VERSION
          git push origin $VERSION

      - name: Upload Packages.gz to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Packages.gz
          tag_name: v1.0.0  # Tag used for the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
